---


### if local is set, the site will use local versions of scripts such as
### bootstrap, jquery, etc. otherwise it will get them from a CDN
#local: true

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
# permalink: / ## disables post output : was messing things up!
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title: "UGA Mathcamp"
keywords:    ""
tagline: "Higher math for high school students." 
description: "The UGA MathCamp provides an opportunity for Athens area high school students learn about topics in
advanced mathematics and interact with students and faculty at the
University of Georgia."
email: ""
source_link: "https://torsor.github.com/mathcamp/"
favicon: ## 
touch_icon: ## 

google_analytics_key: "UA-74515307-2"
## put YOUR key here to enable tracking!
                      ## (blank to disable)

